---
title: "Daniel G. Cerritos Garcia's CV"
author: Daniel G. Cerritos Garcia
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")



# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1BeK8e3BtkxrD4vHi64_Ef0TeOb2TS2zSy6-qr5ZE-Tw/edit#gid=917338460",  
  pdf_mode = params$pdf_mode
)
```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# add side note where to find online version
# if(params$pdf_mode){
  # cat("View this CV online with links at _nickstrayer.me/datadrivencv/_")
# } else {
#  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/nstrayer/cv/raw/master/strayer_cv.pdf)")
# }
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 
Last updated on `r Sys.Date()`.



Main
================================================================================

Daniel G. Cerritos Garcia {#title}
--------------------------------------------------------------------------------


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


Research Experience {data-icon=flask}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('research_positions')
```


Publications {data-icon=file-text-o}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('publications')
```

```{r}
CV %<>% print_links()
```

Posters/Abstracts  {data-icon=sticky-note-o}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('poster')
```
